apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking-server
  template:
    metadata:
      labels:
        app: matchmaking-server
    spec:
      containers:
      - name: matchmaking-server
        image: re5nardo/matchmaking-server:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: matchmaking-server-config