apiVersion: v1
kind: Service
metadata:
  name: matchmaking-server-service
spec:
  selector:
    app: matchmaking-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP